spring.datasource.url=jdbc:postgresql://postgres:15432/petclinic
spring.datasource.username=petclinic
spring.datasource.password=petclinic

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

