global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'petclinic'
    static_configs:
      - targets: ['petclinic-app:9966']

