---
- name: Setup and Deploy Spring PetClinic
  hosts: petclinic
  become: yes

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone repository
      git:
        repo: https://github.com/sar7anola/spring-petclinic.git
        dest: /home/ubuntu/spring-petclinic
        version: main
        force: yes
          
    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: present
        become: yes

    - name: Build and run containers
      shell: |
        cd /home/ubuntu/spring-petclinic
        docker compose down
        docker compose up -d --build
