name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker (with Buildx)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (لو الصور private)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Pull Docker images
      - name: Pull Docker images
        run: docker compose -f docker-compose.yml pull

      # Step 5: Build & Run with Docker Compose
      - name: Build and Run containers
        run: docker compose -f docker-compose.yml up -d --build

      # Step 6: Check running containers
      - name: Check running services
        run: docker ps -a

      # Step 7: Test Spring Petclinic endpoint
      - name: Test Spring Petclinic endpoint
        run: |
          echo "⏳ Waiting for app to start..."
          sleep 40
          curl -f http://localhost:8080 || exit 1

      # Step 8: Cleanup (stop & remove containers, networks, volumes)
      - name: Cleanup Docker
        if: always()
        run: docker compose -f docker-compose.yml down -v
