name: Maven Build with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix mvnw permissions
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw -B verify
        continue-on-error: true   # لو التستس وقعت مش هيوقف الـ job

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: docker compose -f docker-compose.yml up -d --build
